site_name: Mathswiki
theme:
  name: 'material'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Set theory:
      - chapter1: test.md
      - chapter2: test2.md
  - Analysis:
      - Real number: test3.md