site_name: Mathswiki
theme:
  name: 'material'
# mathjax
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
# katex
#markdown_extensions:
#  - pymdownx.arithmatex:
#     generic: true
#
#extra_javascript:
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
#
#extra_css:
#  - https://unpkg.com/katex@0/dist/katex.min.css

# navigator
nav:
  - Home: index.md
  - Set Theory:
      - 1: Set Theory/test.md
      - 2: Set Theory/ZFC/test2.md
  - Analysis: Analysis/test3.md
  - Linear Algebra:
      - 1: Linear Algebra/线性映射基本定理.md
      - 2: Linear Algebra/线性空间的两个定理.md
      - 3: Linear Algebra/习题3B.md
# Chinese search
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'