site_name: Mathswiki
theme:
  name: 'material'
# mathjax
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
# navigator
nav:
  - Home: index.md
  - Set theory:
      - chapter1: test.md
      - chapter2: test2.md
  - Analysis:
      - Real number: test3.md
  - Linear Algebra: 线性映射基本定理.md
# Chinese search
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'